/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type SeoImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Layout = {
  imagePosition?: 'left' | 'right'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type CollectionHubReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'collectionHub'
}

export type LegalDocumentReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'legalDocument'
}

export type ArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'article'
}

export type InformasjonsartikkelReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'informasjonsartikkel'
}

export type InformasjonsdokumentReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'informasjonsdokument'
}

export type EventReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'event'
}

export type ResourceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'resource'
}

export type GridItemLink = {
  title?: string
  type?: string
  internalLink?:
    | PageReference
    | CollectionHubReference
    | LegalDocumentReference
    | ArticleReference
    | InformasjonsartikkelReference
    | InformasjonsdokumentReference
    | EventReference
    | ResourceReference
  url?: string
  email?: string
  phone?: string
  anchor?: string
  newTab?: boolean
}

export type CtaLink = {
  title?: string
  type?: string
  internalLink?:
    | PageReference
    | CollectionHubReference
    | LegalDocumentReference
    | ArticleReference
    | InformasjonsartikkelReference
    | InformasjonsdokumentReference
    | EventReference
    | ResourceReference
  url?: string
  email?: string
  phone?: string
  anchor?: string
  newTab?: boolean
}

export type AppearanceImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "media1" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  title?: string
  description?: string
  altText?: string
  credits?: string
  _type: 'image'
}

export type ContactSectionAppearance = {
  theme?: 'light' | 'dark'
  linkType?: 'link' | 'linkButton'
}

export type Appearance1 = {
  theme?: 'light' | 'dark'
}

export type HeroImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "hero.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  title?: string
  description?: string
  altText?: string
  credits?: string
  _type: 'image'
}

export type InfoMessage = {
  tittel?: string
  tekst?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type CtaSectionAppearance = {
  theme?: 'light' | 'dark'
  linkType?: 'link' | 'linkButton'
  image?: AppearanceImage
  layout?: Layout
}

export type ArticleSectionImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "articleSection.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  title?: string
  description?: string
  altText?: string
  credits?: string
  _type: 'image'
}

export type ArticleSectionAppearance = {
  theme?: 'light' | 'dark'
  linkType?: 'link' | 'linkButton'
  layout?: Layout
}

export type CalloutAppearance = {
  theme?: 'light' | 'dark'
}

export type ImageSectionImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "imageSection.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  title?: string
  description?: string
  altText?: string
  credits?: string
  _type: 'image'
}

export type GridAppearance = {
  theme?: 'light' | 'dark'
}

export type FeaturesLink = {
  title?: string
  type?: string
  internalLink?:
    | PageReference
    | CollectionHubReference
    | LegalDocumentReference
    | ArticleReference
    | InformasjonsartikkelReference
    | InformasjonsdokumentReference
    | EventReference
    | ResourceReference
  url?: string
  email?: string
  phone?: string
  anchor?: string
  newTab?: boolean
}

export type FeaturesAppearance = {
  theme?: 'light' | 'dark'
  linkType?: 'link' | 'linkButton'
  image?: AppearanceImage
}

export type ResourcesAppearance = {
  theme?: 'light' | 'dark'
}

export type TestimonialsLink = {
  title?: string
  type?: string
  internalLink?:
    | PageReference
    | CollectionHubReference
    | LegalDocumentReference
    | ArticleReference
    | InformasjonsartikkelReference
    | InformasjonsdokumentReference
    | EventReference
    | ResourceReference
  url?: string
  email?: string
  phone?: string
  anchor?: string
  newTab?: boolean
}

export type TestimonyImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "testimony.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  title?: string
  description?: string
  altText?: string
  credits?: string
  _type: 'image'
}

export type SectionGroup = {
  _type: 'sectionGroup'
  title?: string
  appearance?: Appearance1
  sections?: Array<
    | {
        title?: string
        body?: string
        image?: HeroImage
        infoMessage?: InfoMessage
        callToActions?: Array<{
          title?: string
          type?: string
          internalLink?:
            | PageReference
            | CollectionHubReference
            | LegalDocumentReference
            | ArticleReference
            | InformasjonsartikkelReference
            | InformasjonsdokumentReference
            | EventReference
            | ResourceReference
          url?: string
          email?: string
          phone?: string
          anchor?: string
          newTab?: boolean
          _key: string
        }>
        _type: 'hero'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        callToActions?: Array<{
          title?: string
          type?: string
          internalLink?:
            | PageReference
            | CollectionHubReference
            | LegalDocumentReference
            | ArticleReference
            | InformasjonsartikkelReference
            | InformasjonsdokumentReference
            | EventReference
            | ResourceReference
          url?: string
          email?: string
          phone?: string
          anchor?: string
          newTab?: boolean
          _key: string
        }>
        appearance?: CtaSectionAppearance
        _type: 'ctaSection'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        callToActions?: Array<{
          title?: string
          type?: string
          internalLink?:
            | PageReference
            | CollectionHubReference
            | LegalDocumentReference
            | ArticleReference
            | InformasjonsartikkelReference
            | InformasjonsdokumentReference
            | EventReference
            | ResourceReference
          url?: string
          email?: string
          phone?: string
          anchor?: string
          newTab?: boolean
          _key: string
        }>
        appearance?: ContactSectionAppearance
        _type: 'contactSection'
        _key: string
      }
    | {
        title?: string
        tittelNivaa?: 'h2' | 'h3'
        tag?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        mediaType?: 'image' | 'iframe'
        image?: ArticleSectionImage
        iframeUrl?: string
        callToActions?: Array<
          {
            _key: string
          } & Link
        >
        appearance?: ArticleSectionAppearance
        _type: 'articleSection'
        _key: string
      }
    | {
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        appearance?: CalloutAppearance
        _type: 'callout'
        _key: string
      }
    | {
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        _type: 'quote'
        _key: string
      }
    | {
        title?: string
        image?: ImageSectionImage
        _type: 'imageSection'
        _key: string
      }
    | {
        title?: string
        tittelNivaa?: 'h2' | 'h3'
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        lists?: Array<
          {
            _key: string
          } & GridList
        >
        appearance?: GridAppearance
        _type: 'grid'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        link?: FeaturesLink
        list?: Array<{
          title?: string
          richText?: Array<
            | {
                children?: Array<{
                  marks?: Array<string>
                  text?: string
                  _type: 'span'
                  _key: string
                }>
                style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                listItem?: 'bullet' | 'number'
                markDefs?: Array<{
                  href?: string
                  _type: 'link'
                  _key: string
                }>
                level?: number
                _type: 'block'
                _key: string
              }
            | {
                asset?: SanityImageAssetReference
                media?: unknown
                hotspot?: SanityImageHotspot
                crop?: SanityImageCrop
                _type: 'image'
                _key: string
              }
          >
          _type: 'feature'
          _key: string
        }>
        appearance?: FeaturesAppearance
        _type: 'features'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        groupedLinks?: Array<
          {
            _key: string
          } & GroupedResources
        >
        appearance?: ResourcesAppearance
        _type: 'resources'
        _key: string
      }
    | {
        logos?: Array<{
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          title?: string
          description?: string
          altText?: string
          credits?: string
          _type: 'image'
          _key: string
        }>
        _type: 'logoSalad'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        link?: TestimonialsLink
        list?: Array<{
          richText?: Array<
            | {
                children?: Array<{
                  marks?: Array<string>
                  text?: string
                  _type: 'span'
                  _key: string
                }>
                style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                listItem?: 'bullet' | 'number'
                markDefs?: Array<{
                  href?: string
                  _type: 'link'
                  _key: string
                }>
                level?: number
                _type: 'block'
                _key: string
              }
            | {
                asset?: SanityImageAssetReference
                media?: unknown
                hotspot?: SanityImageHotspot
                crop?: SanityImageCrop
                _type: 'image'
                _key: string
              }
          >
          name?: string
          company?: string
          image?: TestimonyImage
          _type: 'testimony'
          _key: string
        }>
        _type: 'testimonials'
        _key: string
      }
  >
}

export type GridList = {
  _type: 'gridList'
  title?: string
  columns?: 3 | 4
  kolonnerMobil?: 1 | 2
  contentType?:
    | 'manual'
    | 'writer'
    | 'writer-styret'
    | 'writer-raadgivere'
    | 'writer-frivillige'
    | 'event'
    | 'activities'
    | 'job-position'
    | 'blog-post'
    | 'news'
    | 'walking-tour'
    | 'turvenn'
  items?: Array<
    {
      _key: string
    } & GridItem
  >
  maxItems?: number
  ctaLink?: CtaLink
  bunnTekst?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type GridItem = {
  _type: 'gridItem'
  title?: string
  richText?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  link?: GridItemLink
  image?: AppearanceImage
}

export type GuriAppen = {
  _id: string
  _type: 'guriAppen'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  ingress?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    title?: string
    description?: string
    altText?: string
    credits?: string
    _type: 'image'
  }
  googlePlayUrl?: string
  appStoreUrl?: string
  about?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  argumentsTitle?: string
  arguments?: Array<{
    title?: string
    text?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }
    >
    image?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      title?: string
      description?: string
      altText?: string
      credits?: string
      _type: 'image'
    }
    _type: 'argument'
    _key: string
  }>
  footerSection?: {
    image?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      title?: string
      description?: string
      altText?: string
      credits?: string
      _type: 'image'
    }
    title?: string
    screenshots?: Array<{
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      title?: string
      description?: string
      altText?: string
      credits?: string
      _type: 'image'
      _key: string
    }>
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Blomst = {
  _id: string
  _type: 'blomst'
  _createdAt: string
  _updatedAt: string
  _rev: string
  godkjent?: boolean
  blomstType?: 'snoklokke' | 'alperose' | 'dahlia' | 'krokus' | 'prestekrage' | 'forglemmegei'
  tilMinneOm?: string
  hilsen?: string
  navn?: string
  plantetDato?: string
  vippsOrderId?: string
  donertBeloep?: number
}

export type Redirect = {
  _id: string
  _type: 'redirect'
  _createdAt: string
  _updatedAt: string
  _rev: string
  fromPath?: string
  toPath?: string
  redirectType?: '301' | '302'
  isActive?: boolean
  description?: string
}

export type TurvennReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'turvenn'
}

export type WalkingTour = {
  _id: string
  _type: 'walkingTour'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  dateTime?: string
  location?: string
  turvenn?: TurvennReference
  description?: string
  wheelchairFriendly?: boolean
  strollerFriendly?: boolean
  bringFood?: boolean
  facebookUrl?: string
}

export type Turvenn = {
  _id: string
  _type: 'turvenn'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  city?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    title?: string
    description?: string
    altText?: string
    credits?: string
    _type: 'image'
  }
}

export type GroupedResources = {
  _type: 'groupedResources'
  optionalTitle?: string
  links?: Array<
    {
      _key: string
    } & LinkWithDescription
  >
}

export type LinkWithDescription = {
  _type: 'linkWithDescription'
  title?: string
  description?: string
  type?: string
  internalLink?:
    | PageReference
    | CollectionHubReference
    | LegalDocumentReference
    | ArticleReference
    | InformasjonsartikkelReference
    | InformasjonsdokumentReference
    | EventReference
    | ResourceReference
  url?: string
  email?: string
  phone?: string
  anchor?: string
  newTab?: boolean
}

export type Theme = 'light' | 'dark'

export type Appearance = {
  _type: 'appearance'
  theme?: 'light' | 'dark'
  linkType?: 'link' | 'linkButton'
  image?: AppearanceImage
  layout?: Layout
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
}

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type CompanyInfo = {
  _id: string
  _type: 'companyInfo'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  organizationNumber?: string
  phone?: string
  email?: string
  address?: {
    street?: string
    city?: string
    postalCode?: string
    country?: string
  }
}

export type CallToActionField = {
  _type: 'callToActionField'
  title?: string
  type?: string
  internalLink?:
    | PageReference
    | CollectionHubReference
    | LegalDocumentReference
    | ArticleReference
    | InformasjonsartikkelReference
    | InformasjonsdokumentReference
    | EventReference
    | ResourceReference
  url?: string
  email?: string
  phone?: string
  anchor?: string
  newTab?: boolean
}

export type SoMeLinksReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'soMeLinks'
}

export type FooterSection = {
  _type: 'footerSection'
  sectionTitle?: string
  sectionType?: 'content' | 'socialMedia'
  linksAndContent?: Array<
    | ({
        _key: string
      } & Link)
    | {
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        _type: 'richTextObject'
        _key: string
      }
  >
  socialMediaLinks?: SoMeLinksReference
}

export type SocialMediaLinkID = {
  _type: 'socialMediaLinkID'
  socialMediaUrl?: string
  socialMediaPlatform?: string
}

export type Link = {
  _type: 'link'
  title?: string
  type?: string
  internalLink?:
    | PageReference
    | CollectionHubReference
    | LegalDocumentReference
    | ArticleReference
    | InformasjonsartikkelReference
    | InformasjonsdokumentReference
    | EventReference
    | ResourceReference
  url?: string
  email?: string
  phone?: string
  anchor?: string
  newTab?: boolean
}

export type SoMeLinks = {
  _id: string
  _type: 'soMeLinks'
  _createdAt: string
  _updatedAt: string
  _rev: string
  soMeLinkArray?: Array<
    {
      _key: string
    } & SocialMediaLinkID
  >
}

export type SeoFallback = {
  _id: string
  _type: 'seoFallback'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  keywords?: string
  image?: SeoImage
}

export type NavigationManager = {
  _id: string
  _type: 'navigationManager'
  _createdAt: string
  _updatedAt: string
  _rev: string
  landingPage?: PageReference
  mainMenu?: Array<
    | ({
        _key: string
      } & Link)
    | ({
        _key: string
      } & CallToActionField)
  >
  sidebarMenu?: Array<
    | ({
        _key: string
      } & Link)
    | ({
        _key: string
      } & CallToActionField)
  >
  footerSections?: Array<
    {
      _key: string
    } & FooterSection
  >
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  pageName?: string
  slug?: Slug
  seo?: {
    title?: string
    description?: string
    keywords?: string
    image?: SeoImage
  }
  sections?: Array<
    | {
        title?: string
        body?: string
        image?: HeroImage
        infoMessage?: InfoMessage
        callToActions?: Array<{
          title?: string
          type?: string
          internalLink?:
            | PageReference
            | CollectionHubReference
            | LegalDocumentReference
            | ArticleReference
            | InformasjonsartikkelReference
            | InformasjonsdokumentReference
            | EventReference
            | ResourceReference
          url?: string
          email?: string
          phone?: string
          anchor?: string
          newTab?: boolean
          _key: string
        }>
        _type: 'hero'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        callToActions?: Array<{
          title?: string
          type?: string
          internalLink?:
            | PageReference
            | CollectionHubReference
            | LegalDocumentReference
            | ArticleReference
            | InformasjonsartikkelReference
            | InformasjonsdokumentReference
            | EventReference
            | ResourceReference
          url?: string
          email?: string
          phone?: string
          anchor?: string
          newTab?: boolean
          _key: string
        }>
        appearance?: CtaSectionAppearance
        _type: 'ctaSection'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        callToActions?: Array<{
          title?: string
          type?: string
          internalLink?:
            | PageReference
            | CollectionHubReference
            | LegalDocumentReference
            | ArticleReference
            | InformasjonsartikkelReference
            | InformasjonsdokumentReference
            | EventReference
            | ResourceReference
          url?: string
          email?: string
          phone?: string
          anchor?: string
          newTab?: boolean
          _key: string
        }>
        appearance?: ContactSectionAppearance
        _type: 'contactSection'
        _key: string
      }
    | {
        title?: string
        tittelNivaa?: 'h2' | 'h3'
        tag?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        mediaType?: 'image' | 'iframe'
        image?: ArticleSectionImage
        iframeUrl?: string
        callToActions?: Array<
          {
            _key: string
          } & Link
        >
        appearance?: ArticleSectionAppearance
        _type: 'articleSection'
        _key: string
      }
    | {
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        appearance?: CalloutAppearance
        _type: 'callout'
        _key: string
      }
    | {
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        _type: 'quote'
        _key: string
      }
    | {
        title?: string
        image?: ImageSectionImage
        _type: 'imageSection'
        _key: string
      }
    | {
        title?: string
        tittelNivaa?: 'h2' | 'h3'
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        lists?: Array<
          {
            _key: string
          } & GridList
        >
        appearance?: GridAppearance
        _type: 'grid'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        link?: FeaturesLink
        list?: Array<{
          title?: string
          richText?: Array<
            | {
                children?: Array<{
                  marks?: Array<string>
                  text?: string
                  _type: 'span'
                  _key: string
                }>
                style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                listItem?: 'bullet' | 'number'
                markDefs?: Array<{
                  href?: string
                  _type: 'link'
                  _key: string
                }>
                level?: number
                _type: 'block'
                _key: string
              }
            | {
                asset?: SanityImageAssetReference
                media?: unknown
                hotspot?: SanityImageHotspot
                crop?: SanityImageCrop
                _type: 'image'
                _key: string
              }
          >
          _type: 'feature'
          _key: string
        }>
        appearance?: FeaturesAppearance
        _type: 'features'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        groupedLinks?: Array<
          {
            _key: string
          } & GroupedResources
        >
        appearance?: ResourcesAppearance
        _type: 'resources'
        _key: string
      }
    | {
        logos?: Array<{
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          title?: string
          description?: string
          altText?: string
          credits?: string
          _type: 'image'
          _key: string
        }>
        _type: 'logoSalad'
        _key: string
      }
    | {
        title?: string
        richText?: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<{
                href?: string
                _type: 'link'
                _key: string
              }>
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
            }
        >
        link?: TestimonialsLink
        list?: Array<{
          richText?: Array<
            | {
                children?: Array<{
                  marks?: Array<string>
                  text?: string
                  _type: 'span'
                  _key: string
                }>
                style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                listItem?: 'bullet' | 'number'
                markDefs?: Array<{
                  href?: string
                  _type: 'link'
                  _key: string
                }>
                level?: number
                _type: 'block'
                _key: string
              }
            | {
                asset?: SanityImageAssetReference
                media?: unknown
                hotspot?: SanityImageHotspot
                crop?: SanityImageCrop
                _type: 'image'
                _key: string
              }
          >
          name?: string
          company?: string
          image?: TestimonyImage
          _type: 'testimony'
          _key: string
        }>
        _type: 'testimonials'
        _key: string
      }
    | {
        title?: string
        appearance?: Appearance1
        sections?: Array<
          | {
              title?: string
              body?: string
              image?: HeroImage
              infoMessage?: InfoMessage
              callToActions?: Array<{
                title?: string
                type?: string
                internalLink?:
                  | PageReference
                  | CollectionHubReference
                  | LegalDocumentReference
                  | ArticleReference
                  | InformasjonsartikkelReference
                  | InformasjonsdokumentReference
                  | EventReference
                  | ResourceReference
                url?: string
                email?: string
                phone?: string
                anchor?: string
                newTab?: boolean
                _key: string
              }>
              _type: 'hero'
              _key: string
            }
          | {
              title?: string
              richText?: Array<
                | {
                    children?: Array<{
                      marks?: Array<string>
                      text?: string
                      _type: 'span'
                      _key: string
                    }>
                    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                    listItem?: 'bullet' | 'number'
                    markDefs?: Array<{
                      href?: string
                      _type: 'link'
                      _key: string
                    }>
                    level?: number
                    _type: 'block'
                    _key: string
                  }
                | {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                    _key: string
                  }
              >
              callToActions?: Array<{
                title?: string
                type?: string
                internalLink?:
                  | PageReference
                  | CollectionHubReference
                  | LegalDocumentReference
                  | ArticleReference
                  | InformasjonsartikkelReference
                  | InformasjonsdokumentReference
                  | EventReference
                  | ResourceReference
                url?: string
                email?: string
                phone?: string
                anchor?: string
                newTab?: boolean
                _key: string
              }>
              appearance?: CtaSectionAppearance
              _type: 'ctaSection'
              _key: string
            }
          | {
              title?: string
              richText?: Array<
                | {
                    children?: Array<{
                      marks?: Array<string>
                      text?: string
                      _type: 'span'
                      _key: string
                    }>
                    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                    listItem?: 'bullet' | 'number'
                    markDefs?: Array<{
                      href?: string
                      _type: 'link'
                      _key: string
                    }>
                    level?: number
                    _type: 'block'
                    _key: string
                  }
                | {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                    _key: string
                  }
              >
              callToActions?: Array<{
                title?: string
                type?: string
                internalLink?:
                  | PageReference
                  | CollectionHubReference
                  | LegalDocumentReference
                  | ArticleReference
                  | InformasjonsartikkelReference
                  | InformasjonsdokumentReference
                  | EventReference
                  | ResourceReference
                url?: string
                email?: string
                phone?: string
                anchor?: string
                newTab?: boolean
                _key: string
              }>
              appearance?: ContactSectionAppearance
              _type: 'contactSection'
              _key: string
            }
          | {
              title?: string
              tittelNivaa?: 'h2' | 'h3'
              tag?: string
              richText?: Array<
                | {
                    children?: Array<{
                      marks?: Array<string>
                      text?: string
                      _type: 'span'
                      _key: string
                    }>
                    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                    listItem?: 'bullet' | 'number'
                    markDefs?: Array<{
                      href?: string
                      _type: 'link'
                      _key: string
                    }>
                    level?: number
                    _type: 'block'
                    _key: string
                  }
                | {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                    _key: string
                  }
              >
              mediaType?: 'image' | 'iframe'
              image?: ArticleSectionImage
              iframeUrl?: string
              callToActions?: Array<
                {
                  _key: string
                } & Link
              >
              appearance?: ArticleSectionAppearance
              _type: 'articleSection'
              _key: string
            }
          | {
              richText?: Array<
                | {
                    children?: Array<{
                      marks?: Array<string>
                      text?: string
                      _type: 'span'
                      _key: string
                    }>
                    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                    listItem?: 'bullet' | 'number'
                    markDefs?: Array<{
                      href?: string
                      _type: 'link'
                      _key: string
                    }>
                    level?: number
                    _type: 'block'
                    _key: string
                  }
                | {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                    _key: string
                  }
              >
              appearance?: CalloutAppearance
              _type: 'callout'
              _key: string
            }
          | {
              richText?: Array<
                | {
                    children?: Array<{
                      marks?: Array<string>
                      text?: string
                      _type: 'span'
                      _key: string
                    }>
                    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                    listItem?: 'bullet' | 'number'
                    markDefs?: Array<{
                      href?: string
                      _type: 'link'
                      _key: string
                    }>
                    level?: number
                    _type: 'block'
                    _key: string
                  }
                | {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                    _key: string
                  }
              >
              _type: 'quote'
              _key: string
            }
          | {
              title?: string
              image?: ImageSectionImage
              _type: 'imageSection'
              _key: string
            }
          | {
              title?: string
              tittelNivaa?: 'h2' | 'h3'
              richText?: Array<
                | {
                    children?: Array<{
                      marks?: Array<string>
                      text?: string
                      _type: 'span'
                      _key: string
                    }>
                    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                    listItem?: 'bullet' | 'number'
                    markDefs?: Array<{
                      href?: string
                      _type: 'link'
                      _key: string
                    }>
                    level?: number
                    _type: 'block'
                    _key: string
                  }
                | {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                    _key: string
                  }
              >
              lists?: Array<
                {
                  _key: string
                } & GridList
              >
              appearance?: GridAppearance
              _type: 'grid'
              _key: string
            }
          | {
              title?: string
              richText?: Array<
                | {
                    children?: Array<{
                      marks?: Array<string>
                      text?: string
                      _type: 'span'
                      _key: string
                    }>
                    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                    listItem?: 'bullet' | 'number'
                    markDefs?: Array<{
                      href?: string
                      _type: 'link'
                      _key: string
                    }>
                    level?: number
                    _type: 'block'
                    _key: string
                  }
                | {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                    _key: string
                  }
              >
              link?: FeaturesLink
              list?: Array<{
                title?: string
                richText?: Array<
                  | {
                      children?: Array<{
                        marks?: Array<string>
                        text?: string
                        _type: 'span'
                        _key: string
                      }>
                      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                      listItem?: 'bullet' | 'number'
                      markDefs?: Array<{
                        href?: string
                        _type: 'link'
                        _key: string
                      }>
                      level?: number
                      _type: 'block'
                      _key: string
                    }
                  | {
                      asset?: SanityImageAssetReference
                      media?: unknown
                      hotspot?: SanityImageHotspot
                      crop?: SanityImageCrop
                      _type: 'image'
                      _key: string
                    }
                >
                _type: 'feature'
                _key: string
              }>
              appearance?: FeaturesAppearance
              _type: 'features'
              _key: string
            }
          | {
              title?: string
              richText?: Array<
                | {
                    children?: Array<{
                      marks?: Array<string>
                      text?: string
                      _type: 'span'
                      _key: string
                    }>
                    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                    listItem?: 'bullet' | 'number'
                    markDefs?: Array<{
                      href?: string
                      _type: 'link'
                      _key: string
                    }>
                    level?: number
                    _type: 'block'
                    _key: string
                  }
                | {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                    _key: string
                  }
              >
              groupedLinks?: Array<
                {
                  _key: string
                } & GroupedResources
              >
              appearance?: ResourcesAppearance
              _type: 'resources'
              _key: string
            }
          | {
              logos?: Array<{
                asset?: SanityImageAssetReference
                media?: unknown
                hotspot?: SanityImageHotspot
                crop?: SanityImageCrop
                title?: string
                description?: string
                altText?: string
                credits?: string
                _type: 'image'
                _key: string
              }>
              _type: 'logoSalad'
              _key: string
            }
          | {
              title?: string
              richText?: Array<
                | {
                    children?: Array<{
                      marks?: Array<string>
                      text?: string
                      _type: 'span'
                      _key: string
                    }>
                    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                    listItem?: 'bullet' | 'number'
                    markDefs?: Array<{
                      href?: string
                      _type: 'link'
                      _key: string
                    }>
                    level?: number
                    _type: 'block'
                    _key: string
                  }
                | {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                    _key: string
                  }
              >
              link?: TestimonialsLink
              list?: Array<{
                richText?: Array<
                  | {
                      children?: Array<{
                        marks?: Array<string>
                        text?: string
                        _type: 'span'
                        _key: string
                      }>
                      style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
                      listItem?: 'bullet' | 'number'
                      markDefs?: Array<{
                        href?: string
                        _type: 'link'
                        _key: string
                      }>
                      level?: number
                      _type: 'block'
                      _key: string
                    }
                  | {
                      asset?: SanityImageAssetReference
                      media?: unknown
                      hotspot?: SanityImageHotspot
                      crop?: SanityImageCrop
                      _type: 'image'
                      _key: string
                    }
                >
                name?: string
                company?: string
                image?: TestimonyImage
                _type: 'testimony'
                _key: string
              }>
              _type: 'testimonials'
              _key: string
            }
        >
        _type: 'sectionGroup'
        _key: string
      }
  >
}

export type CollectionHub = {
  _id: string
  _type: 'collectionHub'
  _createdAt: string
  _updatedAt: string
  _rev: string
  type?: 'blog' | 'highlights' | 'news' | 'resources' | 'nettbutikk' | 'minnehagen'
  page?: string
  slug?: Slug
  title?: string
  richText?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    title?: string
    description?: string
    altText?: string
    credits?: string
    _type: 'image'
  }
  contactSection?: {
    title?: string
    richText?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }
    >
    callToActions?: Array<{
      title?: string
      type?: string
      internalLink?:
        | PageReference
        | CollectionHubReference
        | LegalDocumentReference
        | ArticleReference
        | InformasjonsartikkelReference
        | InformasjonsdokumentReference
        | EventReference
        | ResourceReference
      url?: string
      email?: string
      phone?: string
      anchor?: string
      newTab?: boolean
      _key: string
    }>
    appearance?: ContactSectionAppearance
  }
  infoMessage?: {
    tittel?: string
    tekst?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  allPostsLabel?: string
  vippsDonasjoner?: {
    aktivert?: boolean
    tittel?: string
    beskrivelse?: string
    vippsNummer?: string
    innsamlingslenke?: string
    forslagteBeloep?: Array<{
      beloep?: number
      etikett?: string
      _key: string
    }>
    takkeTekst?: string
  }
  callToAction?: {
    title?: string
    type?: string
    internalLink?:
      | PageReference
      | CollectionHubReference
      | LegalDocumentReference
      | ArticleReference
      | InformasjonsartikkelReference
      | InformasjonsdokumentReference
      | EventReference
      | ResourceReference
    url?: string
    email?: string
    phone?: string
    anchor?: string
    newTab?: boolean
  }
  eventsSection?: {
    title?: string
    richText?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }
    >
  }
  availablePositionsSection?: {
    title?: string
    richText?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }
    >
  }
  seo?: {
    title?: string
    description?: string
    keywords?: string
    image?: SeoImage
  }
}

export type Informasjonsdokument = {
  _id: string
  _type: 'informasjonsdokument'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  richText?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  infoMessage?: {
    tittel?: string
    tekst?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  contactSection?: {
    title?: string
    richText?: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }
      | {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
          _key: string
        }
    >
    callToActions?: Array<{
      title?: string
      type?: string
      internalLink?:
        | PageReference
        | CollectionHubReference
        | LegalDocumentReference
        | ArticleReference
        | InformasjonsartikkelReference
        | InformasjonsdokumentReference
        | EventReference
        | ResourceReference
      url?: string
      email?: string
      phone?: string
      anchor?: string
      newTab?: boolean
      _key: string
    }>
    appearance?: ContactSectionAppearance
  }
  slug?: Slug
  allPostsLabel?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    title?: string
    description?: string
    altText?: string
    credits?: string
    _type: 'image'
  }
  seo?: {
    title?: string
    description?: string
    keywords?: string
    image?: SeoImage
  }
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title?: string
  richText?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  link?: {
    title?: string
    type?: string
    internalLink?:
      | PageReference
      | CollectionHubReference
      | LegalDocumentReference
      | ArticleReference
      | InformasjonsartikkelReference
      | InformasjonsdokumentReference
      | EventReference
      | ResourceReference
    url?: string
    email?: string
    phone?: string
    anchor?: string
    newTab?: boolean
  }
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    title?: string
    description?: string
    altText?: string
    credits?: string
    _type: 'image'
  }
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type Resource = {
  _id: string
  _type: 'resource'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  resourceType?:
    | 'article'
    | 'video'
    | 'podcast'
    | 'book'
    | 'website'
    | 'tool'
    | 'guide'
    | 'research'
  externalUrl?: string
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  richText?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  thumbnail?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    title?: string
    description?: string
    altText?: string
    credits?: string
    _type: 'image'
  }
  featured?: boolean
}

export type WriterReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'writer'
}

export type Informasjonsartikkel = {
  _id: string
  _type: 'informasjonsartikkel'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  lead?: string
  richText?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  slug?: Slug
  publishedAt?: string
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  skribent?: WriterReference
  featuredImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    title?: string
    description?: string
    altText?: string
    credits?: string
    _type: 'image'
  }
  seo?: {
    title?: string
    description?: string
    keywords?: string
    image?: SeoImage
  }
}

export type Writer = {
  _id: string
  _type: 'writer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  name?: string
  gruppe?: 'styret' | 'raadgivere' | 'frivillige' | 'skribenter'
  occupation?: string
  email?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    title?: string
    description?: string
    altText?: string
    credits?: string
    _type: 'image'
  }
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  type?: 'blog-post' | 'job-position' | 'news'
  title?: string
  slug?: Slug
  tag?: string
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  lead?: string
  richText?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
  featuredImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    title?: string
    description?: string
    altText?: string
    credits?: string
    _type: 'image'
  }
  seo?: {
    title?: string
    description?: string
    keywords?: string
    image?: SeoImage
  }
}

export type LegalDocument = {
  _id: string
  _type: 'legalDocument'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  richText?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
  >
}

export type BrandAssets = {
  _id: string
  _type: 'brandAssets'
  _createdAt: string
  _updatedAt: string
  _rev: string
  primaryLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  secondaryLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  favicon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SeoImage
  | Layout
  | PageReference
  | CollectionHubReference
  | LegalDocumentReference
  | ArticleReference
  | InformasjonsartikkelReference
  | InformasjonsdokumentReference
  | EventReference
  | ResourceReference
  | GridItemLink
  | CtaLink
  | AppearanceImage
  | ContactSectionAppearance
  | Appearance1
  | HeroImage
  | InfoMessage
  | CtaSectionAppearance
  | ArticleSectionImage
  | ArticleSectionAppearance
  | CalloutAppearance
  | ImageSectionImage
  | GridAppearance
  | FeaturesLink
  | FeaturesAppearance
  | ResourcesAppearance
  | TestimonialsLink
  | TestimonyImage
  | SectionGroup
  | GridList
  | GridItem
  | GuriAppen
  | SanityImageCrop
  | SanityImageHotspot
  | Blomst
  | Redirect
  | TurvennReference
  | WalkingTour
  | Turvenn
  | GroupedResources
  | LinkWithDescription
  | Theme
  | Appearance
  | Category
  | RichText
  | CompanyInfo
  | CallToActionField
  | SoMeLinksReference
  | FooterSection
  | SocialMediaLinkID
  | Link
  | SoMeLinks
  | SeoFallback
  | NavigationManager
  | Page
  | CollectionHub
  | Informasjonsdokument
  | Slug
  | Event
  | CategoryReference
  | Resource
  | WriterReference
  | Informasjonsartikkel
  | Writer
  | Article
  | LegalDocument
  | BrandAssets
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
